spring:
  application:
    name: timesheet-service
  datasource:
    url: jdbc:mysql://${DB_HOST:192.168.0.172}:${DB_PORT:3308}/timesheet
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8345